// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIHxlDazJo7D9SBdb42S6ulj8ihFGVZDI',
    appId: '1:942247664298:web:7840f1fca764d158fbced3',
    messagingSenderId: '942247664298',
    projectId: 'flutterlearn-firebase-tutarial',
    authDomain: 'flutterlearn-firebase-tutarial.firebaseapp.com',
    storageBucket: 'flutterlearn-firebase-tutarial.appspot.com',
    measurementId: 'G-QM6TMCH457',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJK1kKt_XJaRuTpAYQLbQfsAzgvz2bhzM',
    appId: '1:942247664298:android:7eaa7c9ec0002a35fbced3',
    messagingSenderId: '942247664298',
    projectId: 'flutterlearn-firebase-tutarial',
    storageBucket: 'flutterlearn-firebase-tutarial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlElx8QvUH8Nn9Wg0JOr06Lu_AyS0y1LA',
    appId: '1:942247664298:ios:f8e8303c89fc9013fbced3',
    messagingSenderId: '942247664298',
    projectId: 'flutterlearn-firebase-tutarial',
    storageBucket: 'flutterlearn-firebase-tutarial.appspot.com',
    iosClientId: '942247664298-vujfpsv1jkhdodkgir628deg6staeis7.apps.googleusercontent.com',
    iosBundleId: 'com.webneshin.flutterLearningFirebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlElx8QvUH8Nn9Wg0JOr06Lu_AyS0y1LA',
    appId: '1:942247664298:ios:b5e7396674970ee7fbced3',
    messagingSenderId: '942247664298',
    projectId: 'flutterlearn-firebase-tutarial',
    storageBucket: 'flutterlearn-firebase-tutarial.appspot.com',
    iosClientId: '942247664298-hv2k34m9rvk9hkceg8scmh0rghrl6170.apps.googleusercontent.com',
    iosBundleId: 'com.webneshin.flutterLearningFirebaseTutorial.RunnerTests',
  );
}
